name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/unsplash-2sfqpvpj7a0.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-7bK.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-ui5.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-Kpy.png
    - assets/page-1/images/auto-group-n9ft.png
    - assets/page-1/images/auto-group-nqth.png
    - assets/page-1/images/auto-group-nwdb.png
    - assets/page-1/images/status-bar.png
    - assets/page-1/images/group.png
    - assets/page-1/images/component-1.png
    - assets/page-1/images/auto-group-czqb.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-yqF.png
    - assets/page-1/images/auto-group-x7xh.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-66h.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-vZK.png
    - assets/page-1/images/auto-group-ghp1.png
    - assets/page-1/images/auto-group-r5ch.png
    - assets/page-1/images/-MaD.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-VCR.png
    - assets/page-1/images/unsplash-2tv7-o13hgk.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-PVF.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-ffj.png
    - assets/page-1/images/.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-cSZ.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-vCd.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-NL5.png
    - assets/page-1/images/-3x1.png
    - assets/page-1/images/-nq3.png
    - assets/page-1/images/auto-group-8psb.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-oJD.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-fho.png
    - assets/page-1/images/auto-group-meyu.png
    - assets/page-1/images/auto-group-zbu9.png
    - assets/page-1/images/-jUh.png
    - assets/page-1/images/group-rZK.png
    - assets/page-1/images/auto-group-vyy1.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-wm7.png
    - assets/page-1/images/auto-group-smrd.png
    - assets/page-1/images/auto-group-pl4u.png
    - assets/page-1/images/auto-group-vnsf.png
    - assets/page-1/images/unsplash-bgacbj4dqq8.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-Qxm.png
    - assets/page-1/images/auto-group-ocir.png
    - assets/page-1/images/-RmP.png
    - assets/page-1/images/auto-group-usyr.png
    - assets/page-1/images/component-1-aZj.png
    - assets/page-1/images/auto-group-bvcz.png
    - assets/page-1/images/auto-group-ikbb.png
    - assets/page-1/images/status-bar-NkV.png
    - assets/page-1/images/auto-group-2arb.png
    - assets/page-1/images/auto-group-wxzt.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-6Vj.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-yAm.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-czR.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-TsB.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-Tcq.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-A1T.png
    - assets/page-1/images/auto-group-zg3p.png
    - assets/page-1/images/auto-group-bis1.png
    - assets/page-1/images/auto-group-f8uu.png
    - assets/page-1/images/auto-group-apvv.png
    - assets/page-1/images/auto-group-frsf.png
    - assets/page-1/images/component-1-pC5.png
    - assets/page-1/images/status-bar-iYM.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-Prm.png
    - assets/page-1/images/-hsT.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-2Pw.png
    - assets/page-1/images/-pqb.png
    - assets/page-1/images/-9ss.png
    - assets/page-1/images/-tKf.png
    - assets/page-1/images/unsplash-2tv7-o13hgk-sxq.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-hS5.png
    - assets/page-1/images/-ozu.png
    - assets/page-1/images/-wLR.png
    - assets/page-1/images/-UbF.png
    - assets/page-1/images/auto-group-b1hf.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-DBK.png
    - assets/page-1/images/auto-group-c6bf.png
    - assets/page-1/images/auto-group-fc29.png
    - assets/page-1/images/auto-group-assr.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-tBX.png
    - assets/page-1/images/frame-Bem.png
    - assets/page-1/images/mdi-account-circle.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-wGZ.png
    - assets/page-1/images/unsplash-bgacbj4dqq8-v8V.png
    - assets/page-1/images/-Mph.png
    - assets/page-1/images/auto-group-ml2y.png
    - assets/page-1/images/auto-group-dmfk.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-b81.png
    - assets/page-1/images/auto-group-iuoo.png
    - assets/page-1/images/photo2023-03-1623-49-26-removebg-preview-1.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-J61.png
    - assets/page-1/images/auto-group-qk2u.png
    - assets/page-1/images/-Rpq.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-Hs3.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-v9B.png
    - assets/page-1/images/-2CD.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-8W9.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-eUV.png
    - assets/page-1/images/-J8d.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-49j.png
    - assets/page-1/images/auto-group-uxyd.png
    - assets/page-1/images/auto-group-u9i5.png
    - assets/page-1/images/auto-group-yxxr.png
    - assets/page-1/images/auto-group-7rw3.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-BY9.png
    - assets/page-1/images/-gFF.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-n8d.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-H3s.png
    - assets/page-1/images/auto-group-uhoj.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-aYd.png
    - assets/page-1/images/component-1-Sqj.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-6Kw.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-tHj.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-omP.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-uZX.png
    - assets/page-1/images/auto-group-p4kf.png
    - assets/page-1/images/auto-group-yafx.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-nvH.png
    - assets/page-1/images/auto-group-c8jh.png
    - assets/page-1/images/auto-group-71k1.png
    - assets/page-1/images/group-29.png
    - assets/page-1/images/component-2.png
    - assets/page-1/images/unsplash-2sfqpvpj7a0-FL9.png
    - assets/page-1/images/component-3.png
    - assets/page-1/images/auto-group-pc9k.png
    - assets/page-1/images/property-1variant4.png
    - assets/page-1/images/property-1variant4-SFw.png
    - assets/page-1/images/property-1variant2.png
    - assets/page-1/images/property-1variant2-cZ3.png
    - assets/page-1/images/property-1default.png
    - assets/page-1/images/property-1default-Zp9.png
    - assets/page-1/images/status-bar-XGH.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
